ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

github:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "*.md"

module:
  - changed-files:
      - any-glob-to-any-file: "src/mods/**"

types:
  - changed-files:
      - any-glob-to-any-file: "types/**"

tests:
  - changed-files:
      - any-glob-to-any-file: "spec/**"
