---@meta mods.runtime

---
---Lua runtime metadata and version compatibility flags.
---
---## Usage
---
---```lua
---runtime = require "mods.runtime"
---
---print(runtime.version)     --> "Lua 5.x"
---print(runtime.version_num) --> 501 | 502 | 503 | 504 | 505
---print(runtime.is_lua55)    --> true | false
---```
---
---@class mods.runtime
---
---Version string reported by the runtime.
---
---```lua
---print(runtime.version) --> "Lua 5.x"
---```
---
---@field version "Lua 5.1"|"Lua 5.2"|"Lua 5.3"|"Lua 5.4"|"Lua 5.5"
---
---Major version number parsed from `version`.
---
---```lua
---print(runtime.major) --> 5
---```
---
---@field major 5
---
---Minor version number parsed from `version`.
---
---```lua
---print(runtime.minor) --> 1 | 2 | 3 | 4 | 5
---```
---
---@field minor 1|2|3|4|5
---
---Numeric version encoded as `major * 100 + minor`.
---
---```lua
---print(runtime.version_num) --> 501 | 502 | 503 | 504 | 505
---```
---
---@field version_num 501|502|503|504|505
---
---True when running under LuaJIT.
---
---```lua
---print(runtime.is_luajit) --> true | false
---```
---
---@field is_luajit boolean
---
---
---True when running on a Windows host.
---
---```lua
---print(runtime.is_windows) --> true | false
---```
---
---@field is_windows boolean
---
---True only on Lua 5.1 runtimes.
---
---```lua
---print(runtime.is_lua51) --> true | false
---```
---
---@field is_lua51 boolean
---
---True only on Lua 5.2 runtimes.
---
---```lua
---print(runtime.is_lua52) --> true | false
---```
---
---@field is_lua52 boolean
---
---True only on Lua 5.3 runtimes.
---
---```lua
---print(runtime.is_lua53) --> true | false
---```
---
---@field is_lua53 boolean
---
---True only on Lua 5.4 runtimes.
---
---```lua
---print(runtime.is_lua54) --> true | false
---```
---
---@field is_lua54 boolean

---True only on Lua 5.5 runtimes.
---
---```lua
---print(runtime.is_lua55) --> true | false
---```
---
---@field is_lua55 boolean
---
local M = {}

return M
