name: Feature Request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please include context and examples if possible.
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve?
      placeholder: Describe the pain point or missing capability.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What do you want to see added or changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Links, examples, or references.
    validations:
      required: false
