name: Docs / Question
description: Ask a question or request documentation help
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Ask anything about usage, behavior, or documentation.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you want to know?
      placeholder: Be as specific as possible.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add any relevant code, logs, or examples.
      render: shell
    validations:
      required: false
