local stringcase = require("mods.stringcase")

print("snake:", stringcase.snake("HelloWorld"))
print("kebab:", stringcase.kebab("hello_world"))
print("pascal:", stringcase.pascal("hello world"))
print("camel:", stringcase.camel("hello world"))
print("title:", stringcase.title("hello_world"))
print("constant:", stringcase.constant("HelloWorld"))
print("swap:", stringcase.swap("Hello World"))
print("acronym:", stringcase.acronym("Ruby on Rails"))
print("path:", stringcase.path("HelloWorld"))
